name: Create Issue
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
      inputs:
        startdate:
          description: 'Start date (YYYY-MM-DD)'
          required: false
        enddate:
          description: 'End date (YYYY-MM-DD)'
          required: false
jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create an issue via an action
        run: |
          BODY=$(cat .github/content-templates/action-template.md)

          if [ -z "$STARTDATE" ]; then
            STARTDATE=$(date -vmonday "%B-%d")
          fi
          if [ -z "$ENDDATE" ]; then
            ENDDATE=$(date -vfriday "%B-%d, %Y")
          fi

          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "Reflection for $STARTDATE - $ENDDATE" \
            --assignee "$ASSIGNEES" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          ASSIGNEES: ${{ github.repository_owner }}
          LABELS: weekly sync,docs-team
          STARTDATE: ${{ github.event.inputs.startdate }}
          ENDDATE: ${{ github.event.inputs.enddate }}
          PINNED: false
          CLOSE_PREVIOUS: false
